version: '3.3'
services:
  weather-frontend:
    image: weather-app/frontend
    build:
        context: ./frontend
        args:
            OW_USER_TOKEN: ${OW_USER_TOKEN}
    environment:
        - OW_USER_TOKEN=${OW_USER_TOKEN}
    ports:
        - "80:80"
    depends_on:
        - weather-backend
    networks:
      - frontend
  weather-backend:
    image: weather-app/backend
    build: ./backend
    environment:
      - OW_USER_TOKEN=${OW_USER_TOKEN}
      - MONGO_URI=mongodb://${MONGO_USER}:${MONGO_PASS}@mongo:27017
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    networks:
      - backend
      - frontend
  mongo:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
    networks:
      - backend
networks:
  frontend:
  backend:
