---
swagger: "2.0"
info:
  description: "This is the swagger definition of the weather forecast API. For more\
    \ info contact sdimopoulos@irisweb.gr"
  version: "1.0.0"
  title: "Weather Forecast API"
  termsOfService: "http://forecast.irisweb.gr/terms/"
  contact:
    email: "sdimopoulos@irisweb.gr"
  license:
    name: "Proprietary"
    url: "http://forecast.irisweb.gr/license/"
host: "forecast-api.irisweb.gr"
basePath: "/v1"
tags:
- name: "city"
  description: "Current and forecasted weather by city"
- name: "area"
  description: "Areal weather info"
schemes:
- "https"
- "http"
paths:
  /city:
    get:
      tags:
      - "city"
      summary: "Get a list of all cities"
      description: "Returns all available city forecasts"
      operationId: "get_all_city_info"
      produces:
      - "application/json"
      parameters: []
      responses:
        "200":
          description: "success getting response"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/City"
        "400":
          description: "Client error"
        "404":
          description: "City ID not found"
      security:
      - api_key: []
      x-swagger-router-controller: "backend_server.controllers.city_controller"
  /city/{cityId}:
    get:
      tags:
      - "city"
      summary: "Find city by ID"
      description: "Returns a city's weather info"
      operationId: "get_city_info"
      produces:
      - "application/json"
      parameters:
      - name: "cityId"
        in: "path"
        description: "ID of city to return"
        required: true
        type: "integer"
        format: "int32"
      responses:
        "200":
          description: "success getting response"
          schema:
            $ref: "#/definitions/City"
        "400":
          description: "Client error"
        "404":
          description: "City ID not found"
      security:
      - api_key: []
      x-swagger-router-controller: "backend_server.controllers.city_controller"
securityDefinitions:
  api_key:
    type: "apiKey"
    name: "token"
    in: "header"
definitions:
  ForecastInfo:
    type: "object"
    properties:
      daily:
        type: "array"
        description: "Daily overall forecast condition icon Id"
        items:
          type: "string"
          example: "sunny"
      temperature:
        $ref: "#/definitions/ForecastInfo_temperature"
      humidity:
        $ref: "#/definitions/ForecastInfo_humidity"
      pressure:
        $ref: "#/definitions/ForecastInfo_pressure"
    example:
      daily:
      - "sunny"
      - "sunny"
      temperature:
        hourly_graph_url: "temperature_{cityid}.png"
        hourly_forecast:
        - 21.4
        - 21.4
      humidity:
        hourly_graph_url: "humidity_{cityid}.png"
        hourly_forecast:
        - 21.4
        - 21.4
      pressure:
        hourly_graph_url: "pressure_{cityid}.png"
        hourly_forecast:
        - 21.4
        - 21.4
  City:
    type: "object"
    required:
    - "coords"
    - "currWeatherIconId"
    - "name"
    properties:
      id:
        type: "integer"
        format: "int64"
      coords:
        $ref: "#/definitions/City_coords"
      name:
        type: "string"
        example: "Athens"
      currWeatherIconId:
        type: "string"
        example: "sunny"
      forecastInfo:
        $ref: "#/definitions/ForecastInfo"
    example:
      forecastInfo:
        daily:
        - "sunny"
        - "sunny"
        temperature:
          hourly_graph_url: "temperature_{cityid}.png"
          hourly_forecast:
          - 21.4
          - 21.4
        humidity:
          hourly_graph_url: "humidity_{cityid}.png"
          hourly_forecast:
          - 21.4
          - 21.4
        pressure:
          hourly_graph_url: "pressure_{cityid}.png"
          hourly_forecast:
          - 21.4
          - 21.4
      currWeatherIconId: "sunny"
      name: "Athens"
      id: 0
      coords:
        lon: 1.46581298050294517310021547018550336360931396484375
        lat: 6.02745618307040320615897144307382404804229736328125
  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      type:
        type: "string"
      message:
        type: "string"
  ForecastInfo_temperature:
    type: "object"
    properties:
      hourly_graph_url:
        type: "string"
        example: "temperature_{cityid}.png"
        description: "Url of temperature forecast graph"
      hourly_forecast:
        type: "array"
        items:
          type: "number"
          example: 21.4
          description: "Hourly forecast"
    example:
      hourly_graph_url: "temperature_{cityid}.png"
      hourly_forecast:
      - 21.4
      - 21.4
  ForecastInfo_humidity:
    type: "object"
    properties:
      hourly_graph_url:
        type: "string"
        example: "humidity_{cityid}.png"
        description: "Url of humidity forecast graph"
      hourly_forecast:
        type: "array"
        items:
          type: "number"
          example: 21.4
          description: "Hourly forecast"
    example:
      hourly_graph_url: "humidity_{cityid}.png"
      hourly_forecast:
      - 21.4
      - 21.4
  ForecastInfo_pressure:
    type: "object"
    properties:
      hourly_graph_url:
        type: "string"
        example: "pressure_{cityid}.png"
        description: "Url of pressure forecast graph"
      hourly_forecast:
        type: "array"
        items:
          type: "number"
          example: 21.4
          description: "Hourly forecast"
    example:
      hourly_graph_url: "pressure_{cityid}.png"
      hourly_forecast:
      - 21.4
      - 21.4
  City_coords:
    type: "object"
    required:
    - "lat"
    - "lon"
    properties:
      lat:
        type: "number"
      lon:
        type: "number"
    example:
      lon: 1.46581298050294517310021547018550336360931396484375
      lat: 6.02745618307040320615897144307382404804229736328125
