# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from backend_server.models.base_model_ import Model
from backend_server import util


class CityCoords(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, lat: float=None, lon: float=None):  # noqa: E501
        """CityCoords - a model defined in Swagger

        :param lat: The lat of this CityCoords.  # noqa: E501
        :type lat: float
        :param lon: The lon of this CityCoords.  # noqa: E501
        :type lon: float
        """
        self.swagger_types = {
            'lat': float,
            'lon': float
        }

        self.attribute_map = {
            'lat': 'lat',
            'lon': 'lon'
        }

        self._lat = lat
        self._lon = lon

    @classmethod
    def from_dict(cls, dikt) -> 'CityCoords':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The City_coords of this CityCoords.  # noqa: E501
        :rtype: CityCoords
        """
        return util.deserialize_model(dikt, cls)

    @property
    def lat(self) -> float:
        """Gets the lat of this CityCoords.


        :return: The lat of this CityCoords.
        :rtype: float
        """
        return self._lat

    @lat.setter
    def lat(self, lat: float):
        """Sets the lat of this CityCoords.


        :param lat: The lat of this CityCoords.
        :type lat: float
        """
        if lat is None:
            raise ValueError("Invalid value for `lat`, must not be `None`")  # noqa: E501

        self._lat = lat

    @property
    def lon(self) -> float:
        """Gets the lon of this CityCoords.


        :return: The lon of this CityCoords.
        :rtype: float
        """
        return self._lon

    @lon.setter
    def lon(self, lon: float):
        """Sets the lon of this CityCoords.


        :param lon: The lon of this CityCoords.
        :type lon: float
        """
        if lon is None:
            raise ValueError("Invalid value for `lon`, must not be `None`")  # noqa: E501

        self._lon = lon
